os: linux
language: python
python: "3.7"
dist: xenial
compiler: 
- clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
install:
- pip install conan
- conan user
script:
- export CC=gcc-9
- export CXX=g++-9
- conan install .
- cmake . -G "Unix Makefiles"
- make
- ctest -C Debug
- ctest -C Release
